# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Label1
on: [push]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Cache Node.js Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: | 
            npm-${{ runner.os }}-

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npx semantic-release  
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #  - uses: actions/labeler@v4
       # with:
       #   GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
